### PR TITLE
fixed #17 gulp

### LINKED ISSUE #17: gulp.js
Combine and minify JS and CSS files.

### PR DESCRIPTION
**Pull request by rovinglight**

### CODE REVIEW

**Comment by ztl8702** [comment]
I got this when running `bower install`:

```
Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#1.5.0 which resolved to 1.5.0 and is required by angular-route#1.5.0,foochow-idioms
    2) angular#1.6.4 which resolved to 1.6.4 and is required by ng-office-ui-fabric#0.15.3

Prefix the choice with ! to persist it to bower.json

? Answer
```

**Comment by rovinglight** [comment]
We should use the first one. It may caused by a wrong package name in bower.json.We were using ```office-ui-fabric``` not ```ng-office-ui-fabric```. The first selection will download the right package, so use it temporarily. I can fix that tonight. Sorry for the bug( ✘_✘ )↯

**Comment by rovinglight** [comment]
@ztl8702 Things should be fine by now ~

**Comment by ztl8702** [comment]
Auto-reload not yet implemented.  Need to run `gulp serve` every time the code changes.

**Pull request merged**
